### PR TITLE
Adapt it for react-native@0.56.0

### PR DESCRIPTION
**Pull request by hugohow**
Delete ActivityIndicator Proptypes, and add new Proptypes for ProgressDialog

### CODE REVIEW

**Comment by douglasjunior** [comment]
Thanks!

**Comment by hugohow** [comment]
@douglasjunior can you publish the new version ? Thanks :)

**Comment by douglasjunior** [comment]
Done, version 0.4.0

**Comment by hugohow** [comment]
Thanks @douglasjunior

**Pull request merged**
